# Generated by Django 4.2.6 on 2024-07-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='address',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Storage Name'),
        ),
    ]
