# Generated by Django 4.2.6 on 2024-07-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='agent',
            new_name='agents',
        ),
    ]
