# Generated by Django 4.2.6 on 2024-07-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_rename_agent_campaign_agents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='end_date',
        ),
        migrations.AddField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
