# Generated by Django 4.2.6 on 2024-07-31 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_remove_slot_end_date_slot_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='start_date',
            new_name='start_time',
        ),
    ]
