# Generated by Django 4.2.6 on 2024-10-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_rename_start_date_slot_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='max_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='reserved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
