# Generated by Django 4.2.6 on 2024-07-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='is_vaccinated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
