# Generated by Django 4.2.6 on 2024-10-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Identity_document_number',
            new_name='identity_document_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Identity_document_type',
            new_name='identity_document_type',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mIddle_name',
            new_name='middle_name',
        ),
    ]
