# Generated by Django 4.2.6 on 2024-07-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='interval',
            field=models.IntegerField(default=0, help_text='Please provide interval in days.'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Vaccine Name'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='storage_temperature',
            field=models.IntegerField(blank=True, help_text='Provide the temperature in Celcius.', null=True),
        ),
    ]
